### PR TITLE
GeneralStore.defineFactory()

### PR DESCRIPTION
**Pull request by colbyr**
The objective here is twofold:

1. I want allow for more testable stores without jumping through hoops
2. I want stores to be more composable: we've been writing writing helpers like `defineMapStore` or `defineSearchStore`, but there's no real way to combine common store patterns into one store because the state is only kept in the closure.

This PR adds a new `defineFactory` API:

```javascript
const APIStoreData = Record({
  pending: Map(),
  cache: Map(),
});
const UPDATE_ACTION = 'SEARCH_COMPLETE';
function defineAPIStore(apiURL) {
  return GeneralStore.defineFactory()
    .defineInitialData(APIStoreData())
    .defineGet((state, id) => {
      const result = state.getIn(['cache', id]);
      if (!result && !state.hasIn(['pending', id])) {
        fetch(apiURL, id).then(data => dispatch(UPDATE_ACTION, {id, data}));
      }
      return result;
    })
    .defineResponseTo(UPDATE_ACTION, (state, {id, data}) => {
      return state
        .removeIn(['pending', id])
        .setIn(['cache', id], data);
    })
}
```

This doesn't look much different than what we could accomplish with `GeneralStore.define()`, but the exciting stuff comes later when we can add additional actions that can access the store's state as well!

```javascript
const UserStore = defineAPIStore('/usersById')
  .defineResponseTo(USER_NAME_UPDATED, (state, {id, newName}) => {
    return state.setIn(['cache', id, 'name'], newName);
  })
  .register();
```

As far as testing goes, `StoreFactory.register()` returns a new `Store` instance every time, so you can call it as many times as you want. Since the state is stored on the instance you don't need to worry about trying to reset it or forcing your module to re-eval.

`Store` also has a `getFactory` method so if you want to export a store as a singleton you can do so and still get the benefits of using a factory at test time:

*EDIT: looks like I forgot to actually build `getFactory`... but I can if we think its a good idea :stuck_out_tongue:*

```javascript
import UserStore from 'UserStore';
describe('UserStore', () => {
  let storeInstance;
  beforeEach(() => {
    storeInstance = UserStore.getFactory().register();
  });
});
```

cc @gusvargas @marcneuwirth @banderson @timmfin @also you guys have any thoughts?

### CODE REVIEW

**Comment by gusvargas** [comment]
This is a cool. Do you think that `GeneralStore` should also provide some plumbing for exposing store instances to container components? Could we modify `StoreDependencyMixin` to pull stores from `this.context`?

IMO, this is a good improvement but now it seems like it's lacking something to tie it all together.

**Comment by colbyr** [comment]
I'd be open to exploring that. I am interested in a more "HOC" style alternative to the `StoreDependencyMixin`. I think that line of exploration (in a future PR) would be the right time to check out what `context` has to offer us.

@gusvargas what exactly would you be looking to get out of that sort of plumbing?

**Comment by gusvargas** [comment]
@colbyr At a high level I just want to be able to get a handle on store instances (for use in StoreDepMixin) without having to write the boilerplate, e.g., creating some `stores` object and wiring up the injecting into components via context, props, or whatever.

**Comment by colbyr** [comment]
I'm feeling pretty good about this. Unless anyone has any objects I'll probably merge on Monday.

**Comment by also** [comment]
:money_with_wings:

**Pull request merged**
